In [24]:
import torch
pe = torch.zeros(3, 4)
print(pe)
print(pe[:, 0::2])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [39]:
a = torch.rand(5,5)
print(a)
print(a[0::2, 0::2])
print(a[:, 1::2])

tensor([[0.2450, 0.1392, 0.1701, 0.5277, 0.0585],
        [0.7296, 0.1069, 0.3843, 0.4307, 0.0247],
        [0.9730, 0.3994, 0.7793, 0.9848, 0.0994],
        [0.0779, 0.0841, 0.9034, 0.2271, 0.9575],
        [0.6973, 0.8810, 0.7524, 0.4624, 0.3419]])
tensor([[0.2450, 0.1701, 0.0585],
        [0.9730, 0.7793, 0.0994],
        [0.6973, 0.7524, 0.3419]])
tensor([[0.1392, 0.5277],
        [0.1069, 0.4307],
        [0.3994, 0.9848],
        [0.0841, 0.2271],
        [0.8810, 0.4624]])


In [12]:
torch.arange(0, 10, dtype = torch.float).unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [19]:
import math
-math.log(10000.0)

-9.210340371976184

In [49]:
seq_len, d_model = 5, 6
pe = torch.zeros(seq_len, d_model) 

# Creating a tensor representing positions (0 to seq_len - 1)
position = torch.arange(0, seq_len, dtype = torch.float).unsqueeze(1) # Transforming 'position' into a 2D tensor['seq_len, 1']

# Creating the division term for the positional encoding formula
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

# Apply sine to even indices in pe
pe[:, 0::2] = torch.sin(position * div_term)
# Apply cosine to odd indices in pe
pe[:, 1::2] = torch.cos(position * div_term)
pe.unsqueeze(0)

tensor([[[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
         [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
         [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
         [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
         [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000]]])