In [1]:
import torch
pe = torch.zeros(3, 4)
print(pe)
print(pe[:, 0::2])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [59]:
a = torch.rand(3,5)
a.shape[1]

5

In [12]:
torch.arange(0, 10, dtype = torch.float).unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [19]:
import math
-math.log(10000.0)

-9.210340371976184

In [60]:
seq_len, d_model = 5, 6
pe = torch.zeros(seq_len, d_model) 

# Creating a tensor representing positions (0 to seq_len - 1)
position = torch.arange(0, seq_len, dtype = torch.float).unsqueeze(1) # Transforming 'position' into a 2D tensor['seq_len, 1']

# Creating the division term for the positional encoding formula
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

# Apply sine to even indices in pe
pe[:, 0::2] = torch.sin(position * div_term)
# Apply cosine to odd indices in pe
pe[:, 1::2] = torch.cos(position * div_term)
pe = pe.unsqueeze(0)


In [63]:
batch_size, seq_len, d_model =2, 5, 6
pe = torch.zeros(batch_size, seq_len, d_model) 
pe.shape[2]

6

In [80]:
from embedding.pt_position import PositionalEncoding

pos_encoding = PositionalEncoding(d_model=512, seq_len=10, dropout=0.1)
print(pos_encoding.pe.shape)
x = torch.rand(5, 10, 512)
output = pos_encoding(x)
output.shape

torch.Size([1, 10, 512])


torch.Size([5, 10, 512])

In [95]:

import numpy as np
import math

d_model = 512
seq_len = 10

position = np.arange(seq_len, dtype=float)[:, np.newaxis] 
div_term = np.exp(np.arange(0, d_model, 2, dtype=float)) #* -(np.log(10000.0) / d_model))
pe = np.zeros((seq_len, d_model))
pe[:, 0::2] = np.sin(position * div_term)
# Apply cosine to odd indices in pe
pe[:, 1::2] = np.cos(position * div_term)
pe = np.expand_dims(pe, axis=0)
pe.shape
# x = np.random.rand(5, 10, 512)

pe[:, :x.shape[1]].shape

(1, 10, 512)

In [96]:
import numpy as np

# pe 배열: (1, 4, 3) 형태의 3차원 배열
pe = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

# x 배열: (2, 2, 3) 형태의 3차원 배열
x = np.random.rand(2, 2, 3)

# pe[:, :x.shape[1]] 사용
result1 = pe[:, :x.shape[1]]
print(result1)
print("Shape of result1:", result1.shape)

# pe[:, :x.shape[1], :] 사용
result2 = pe[:, :x.shape[1], :]
print(result2)
print("Shape of result2:", result2.shape)

[[[1 2 3]
  [4 5 6]]]
Shape of result1: (1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
Shape of result2: (1, 2, 3)


In [115]:

import numpy as np
import torch
import torch.nn as nn

eps = 10**-6
x = torch.tensor(np.random.rand(2, 10, 512), dtype=torch.float32)
alpha = nn.Parameter(torch.ones(1)) # One-dimensional tensor that will be used to scale the input data

bias = nn.Parameter(torch.zeros(1)) # One-dimensional tenso that will be added to the input data
alpha, bias

mean = x.mean(dim = -1, keepdim = True) # Computing the mean of the input data. Keeping the number of dimensions unchanged
std = x.std(dim = -1, keepdim = True) # Computing the standard deviation of the input data. Keeping the number of dimensions unchanged
        
alpha * (x-mean) / (std + eps) + bias

tensor([[[ 1.8974e-02, -3.7333e-01, -1.2893e+00,  ..., -1.0914e+00,
          -1.4434e+00, -4.5408e-01],
         [-9.6912e-01,  1.4086e+00, -3.6165e-01,  ...,  7.4841e-02,
          -4.1845e-01,  4.6434e-04],
         [ 1.8011e+00,  1.6231e+00,  9.6974e-01,  ...,  2.4877e-01,
           8.8367e-01,  1.0459e-01],
         ...,
         [ 1.5495e+00, -2.4305e-01,  1.1839e+00,  ..., -7.5035e-01,
          -1.0053e+00,  6.2943e-01],
         [ 5.8528e-01,  1.1627e-01, -4.7579e-01,  ..., -7.7362e-01,
           2.3335e-01, -3.1856e-02],
         [ 1.0478e+00,  1.6069e+00, -1.4900e+00,  ..., -3.6156e-01,
          -4.6621e-01,  1.1313e+00]],

        [[ 1.4661e+00, -9.2386e-02,  1.3521e+00,  ...,  3.2525e-01,
          -6.6381e-01, -9.4885e-01],
         [ 1.4223e+00, -1.4152e+00, -1.3470e+00,  ...,  4.6218e-01,
           1.2839e+00, -1.2251e+00],
         [ 4.8338e-01,  1.5696e+00, -7.2131e-01,  ..., -6.4744e-01,
           8.2422e-03, -6.0463e-01],
         ...,
         [-1.6825e+00,  1

In [114]:
import numpy as np
import torch
import torch.nn as nn

eps = 10**-6
alpha = np.ones((1,)) 
bias = np.zeros((1,))
x = np.random.rand(2, 10, 512)
mean = x.mean(axis = -1, keepdims=True) # Computing the mean of the input data. Keeping the number of dimensions unchanged
std = x.std(axis = -1, keepdims=True) # Computing the standard deviation of the input data. Keeping the number of dimensions unchanged
        
alpha * (x-mean) / (std + eps) + bias

array([[[ 1.406948  ,  1.25346707, -0.42135117, ..., -0.97828444,
          1.6543173 , -0.46640261],
        [ 0.59150044,  0.99039293, -0.40004363, ...,  0.21679665,
         -0.37536094,  0.17018866],
        [-0.90687934,  0.31464981, -0.90301743, ...,  0.65993653,
         -1.31050138,  0.54569101],
        ...,
        [-1.21250908, -0.27937219, -0.00859462, ..., -0.19181777,
          1.17208064,  1.01407876],
        [-0.01594736, -0.2376258 ,  1.3790151 , ...,  1.01714823,
          0.70535331,  0.12603634],
        [-0.29881791, -1.56283988, -0.63784847, ...,  1.31632397,
         -1.31980812,  1.00559515]],

       [[-1.49989245,  1.02475926, -0.1921105 , ..., -0.04745001,
         -1.34603429, -0.78242785],
        [-0.70973579,  1.41222795, -0.24558219, ...,  0.42040351,
          0.5467505 , -0.28627766],
        [ 0.91151198, -0.03843883, -0.51292036, ..., -1.30789123,
         -0.96578559,  0.10643825],
        ...,
        [ 1.590901  , -0.60996341, -0.20250717, ...,  

## feed forward test

In [30]:
import numpy as np

class Dropout:
    def __init__(self, dropout_rate=0.5):
        self.dropout_rate = dropout_rate
        self.mask = None
    
    def forward(self, x, train_flag=True):
        # 학습 시
        if train_flag:
            self.mask = np.random.rand(*x.shape) > self.dropout_rate
            return x * self.mask
        else:
            return x * (1.0 - self.dropout_rate)
    
    def backward(self, dout):
        return dout * self.mask

class ReLU:
    
    def __init__(self):
        pass
    
    def forward(self, x):
        return np.maximum(0, x)
    
    def backward(self, x, grad_output):
        relu_grad = x > 0
        return grad_output * relu_grad

class FeedForwardBlock:
    
    def __init__(self, d_model: int, d_ff: int, dropout: float) -> None:
        # forward만 구현, random한 값으로 임의 init
        self.W1 = np.random.randn(d_model, d_ff) 
        self.b1 = np.random.randn(d_ff)
        self.W2 = np.random.randn(d_ff, d_model)
        self.b2 = np.random.randn(d_model)
        
        self.actiavation = ReLU()
        self.dropout = Dropout(dropout)
        
    def forward(self, x):
        # (Batch, seq_len, d_model) --> (batch, seq_len, d_ff)
        linear_1 = self.dropout.forward(self.actiavation.forward(np.dot(x, self.W1) + self.b1))
        
        # (batch, seq_len, d_ff) -->(batch, seq_len, d_model)
        linear_2 = np.dot(linear_1, self.W2) + self.b2
        return linear_2

FeedForwardBlock(512, 2048, 0.1).forward(np.random.rand(2, 10, 512)).shape

(2, 10, 512)

# attention

In [37]:
# qyery, key, value shape: (batch_size, seq_len, d_k)
# mask shape: (batch_size, seq_len, seq_len)

query, key, value = np.random.rand(1, 2, 5), np.random.rand(1, 2, 5), np.random.rand(1, 2, 5)
mask = np.random.rand(1, 2, 2) > 0.5
scores = np.matmul(query, key.transpose(0,2,1)) / np.sqrt(query.shape[-1])
print(mask)
if mask is not None:
    scores = np.where(mask == 0, -1e9, scores)
    print(scores)

[[[False  True]
  [False  True]]]
[[[-1.00000000e+09  2.83581647e-01]
  [-1.00000000e+09  1.31930548e-01]]]


In [43]:
linear_layers = [np.empty((d_model, d_model)) for _ in range(3)]
output_linear = np.empty((d_model, d_model))
linear_layers

[array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  7.85563972e+00],
        [ 1.76643157e+01,  1.46192234e+01,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  2.55480712e+00,  0.00000000e+00, ...,
          6.89829850e+00,  0.00000000e+00,  1.26354108e+01],
        ...,
        [ 9.66596886e-15, -1.07562426e-14,  3.13325998e-15, ...,
          1.81881504e-16, -1.67811657e-24,  8.07759595e-17],
        [-1.57444034e-24, -5.52962824e-14,  7.06011442e-20, ...,
          1.99687779e-14,  1.85037209e-28,  1.90711330e-14],
        [ 1.75828430e-19, -7.85220312e-17, -2.43488462e-14, ...,
         -1.08633817e-15,  3.42086588e-16, -4.00137991e-16]]),
 array([[ 0.72033332,  0.53810897,  2.00715621, ..., -0.1953115 ,
          0.92959405,  0.02986244],
        [-0.23327125, -0.80713075, -0.24969228, ...,  0.62572568,
         -0.11806169, -0.75471715],
        [-0.54308314, -0.

In [67]:
import numpy as np

def softmax(x, dim=None):
    # x - np.max(x, axis=dim, keepdims=True)는 지수 함수의 지수가 너무 크거나 작아지는 것을 방지하기 위함
    # keepdims=True는 차원을 유지하겠다는 의미
    e_x = np.exp(x - np.max(x, axis=dim, keepdims=True))
    return e_x / e_x.sum(axis=dim, keepdims=True)

class Attention:
    def forward(self, query, key, value, mask=None, dropout=None):
        # query, key, value shape: (batch_size, seq_len, d_k)
        # mask shape: (batch_size, seq_len, seq_len)
        scores = np.matmul(query, key.transpose(0,1,3,2)) / np.sqrt(query.shape[-1])
        # make가 0인 부분은 -1e9로 채워준다.
        if mask is not None:
            scores = np.where(mask == 0, -1e9, scores)
        # softmax 적용
        p_attn = softmax(scores, dim=-1)
        
        if dropout is not None:
            p_attn = dropout.forward(p_attn)
            
        return np.matmul(p_attn, value), p_attn
    
class MultiHeadedAttention:
    def __init__(self, h, d_model, dropout=0.1):
        assert d_model % h == 0
        
        self.d_k = d_model // h
        self.h = h
        
        self.linear_layers = [np.random.randn(d_model, d_model) for _ in range(3)]
        self.output_linear = np.random.randn(d_model, d_model)
        self.attention = Attention()
        
        self.dropout = Dropout(dropout)
    
    def forward(self, query, key, value, mask=None):
        # query, key, value: (batch_size, seq_len, d_embed)
        # mask: (batch_size, seq_len, seq_len)
        
        batch_size = query.shape[0]
        
        # 1) Do all the linear projections in batch from d_model => h x d_k
        # query, key, value: (batch_size, seq_len, h, d_k) -> (batch_size, h, seq_len, d_k)
        query, key, value = [np.matmul(x, l).reshape(batch_size, -1, self.h, self.d_k).transpose(0, 2, 1, 3) \
                                for l, x in zip(self.linear_layers, (query, key, value))]

        # 2) Apply attention on all the projected vectors in batch.
        # x: (batch_size, h, seq_len, d_k)
        x, attn = self.attention.forward(query, key, value, mask=mask, dropout=self.dropout)

        # 3) "Concat" using a view and apply a final linear.
        # x: (batch_size, seq_len, h, d_k) -> (batch_size, seq_len, h*d_k = d_model)
        x = x.transpose(0, 2, 1, 3).reshape(batch_size, -1, self.h * self.d_k)
        print(x.shape)
        return np.matmul(x, self.output_linear)

x = MultiHeadedAttention(8, 512, 0).forward(np.random.rand(1, 2, 512), np.random.rand(1, 2, 512), np.random.rand(1, 2, 512)).shape

(1, 2, 512)


## residual connection

In [81]:
import numpy as np

class Dropout:
    def __init__(self, dropout_rate=0.5):
        self.dropout_rate = dropout_rate
        self.mask = None
    
    def forward(self, x, train_flag=True):
        # 학습 시
        if train_flag:
            self.mask = np.random.rand(*x.shape) > self.dropout_rate
            return x * self.mask
        else:
            return x * (1.0 - self.dropout_rate)
    
    def backward(self, dout):
        return dout * self.mask
    
class LayerNormalization:
    
    def __init__(self, eps: float = 10**-6): # We define epsilon as 0.000001 to avoid division by zero
        self.eps = eps
        
        # 학습은 구현 안함
        self.alpha = np.ones((1,)) 
        self.bias = np.zeros((1,))
        
    def forward(self, x):
        mean = x.mean(axis = -1, keepdims = True) # Computing the mean of the input data. Keeping the number of dimensions unchanged
        std = x.std(axis = -1, keepdims = True) # Computing the standard deviation of the input data. Keeping the number of dimensions unchanged
        
        # Returning the normalized input
        return self.alpha * (x-mean) / (std + self.eps) + self.bias

import torch.nn as nn
from .layer_norm import LayerNormalization
from .dropout import Dropout

class ResidualConnection:
    """
    A residual connection followed by a layer norm.
    Note for code simplicity the norm is first as opposed to last.
    """

    def __init__(self, size, dropout):
        self.norm = LayerNormalization(size)
        self.dropout = Dropout(dropout)

    def forward(self, x, sublayer):
        "Apply residual connection to any sublayer with the same size."
        return x + self.dropout.forward(sublayer(self.norm(x)))



(1, 2, 512)