In [1]:
import torch
pe = torch.zeros(3, 4)
print(pe)
print(pe[:, 0::2])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [59]:
a = torch.rand(3,5)
a.shape[1]

5

In [12]:
torch.arange(0, 10, dtype = torch.float).unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [19]:
import math
-math.log(10000.0)

-9.210340371976184

In [60]:
seq_len, d_model = 5, 6
pe = torch.zeros(seq_len, d_model) 

# Creating a tensor representing positions (0 to seq_len - 1)
position = torch.arange(0, seq_len, dtype = torch.float).unsqueeze(1) # Transforming 'position' into a 2D tensor['seq_len, 1']

# Creating the division term for the positional encoding formula
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

# Apply sine to even indices in pe
pe[:, 0::2] = torch.sin(position * div_term)
# Apply cosine to odd indices in pe
pe[:, 1::2] = torch.cos(position * div_term)
pe = pe.unsqueeze(0)


In [63]:
batch_size, seq_len, d_model =2, 5, 6
pe = torch.zeros(batch_size, seq_len, d_model) 
pe.shape[2]

6

In [80]:
from embedding.pt_position import PositionalEncoding

pos_encoding = PositionalEncoding(d_model=512, seq_len=10, dropout=0.1)
print(pos_encoding.pe.shape)
x = torch.rand(5, 10, 512)
output = pos_encoding(x)
output.shape

torch.Size([1, 10, 512])


torch.Size([5, 10, 512])

In [95]:

import numpy as np
import math

d_model = 512
seq_len = 10

position = np.arange(seq_len, dtype=float)[:, np.newaxis] 
div_term = np.exp(np.arange(0, d_model, 2, dtype=float)) #* -(np.log(10000.0) / d_model))
pe = np.zeros((seq_len, d_model))
pe[:, 0::2] = np.sin(position * div_term)
# Apply cosine to odd indices in pe
pe[:, 1::2] = np.cos(position * div_term)
pe = np.expand_dims(pe, axis=0)
pe.shape
# x = np.random.rand(5, 10, 512)

pe[:, :x.shape[1]].shape

(1, 10, 512)

In [96]:
import numpy as np

# pe 배열: (1, 4, 3) 형태의 3차원 배열
pe = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

# x 배열: (2, 2, 3) 형태의 3차원 배열
x = np.random.rand(2, 2, 3)

# pe[:, :x.shape[1]] 사용
result1 = pe[:, :x.shape[1]]
print(result1)
print("Shape of result1:", result1.shape)

# pe[:, :x.shape[1], :] 사용
result2 = pe[:, :x.shape[1], :]
print(result2)
print("Shape of result2:", result2.shape)

[[[1 2 3]
  [4 5 6]]]
Shape of result1: (1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
Shape of result2: (1, 2, 3)


In [115]:

import numpy as np
import torch
import torch.nn as nn

eps = 10**-6
x = torch.tensor(np.random.rand(2, 10, 512), dtype=torch.float32)
alpha = nn.Parameter(torch.ones(1)) # One-dimensional tensor that will be used to scale the input data

bias = nn.Parameter(torch.zeros(1)) # One-dimensional tenso that will be added to the input data
alpha, bias

mean = x.mean(dim = -1, keepdim = True) # Computing the mean of the input data. Keeping the number of dimensions unchanged
std = x.std(dim = -1, keepdim = True) # Computing the standard deviation of the input data. Keeping the number of dimensions unchanged
        
alpha * (x-mean) / (std + eps) + bias

tensor([[[ 1.8974e-02, -3.7333e-01, -1.2893e+00,  ..., -1.0914e+00,
          -1.4434e+00, -4.5408e-01],
         [-9.6912e-01,  1.4086e+00, -3.6165e-01,  ...,  7.4841e-02,
          -4.1845e-01,  4.6434e-04],
         [ 1.8011e+00,  1.6231e+00,  9.6974e-01,  ...,  2.4877e-01,
           8.8367e-01,  1.0459e-01],
         ...,
         [ 1.5495e+00, -2.4305e-01,  1.1839e+00,  ..., -7.5035e-01,
          -1.0053e+00,  6.2943e-01],
         [ 5.8528e-01,  1.1627e-01, -4.7579e-01,  ..., -7.7362e-01,
           2.3335e-01, -3.1856e-02],
         [ 1.0478e+00,  1.6069e+00, -1.4900e+00,  ..., -3.6156e-01,
          -4.6621e-01,  1.1313e+00]],

        [[ 1.4661e+00, -9.2386e-02,  1.3521e+00,  ...,  3.2525e-01,
          -6.6381e-01, -9.4885e-01],
         [ 1.4223e+00, -1.4152e+00, -1.3470e+00,  ...,  4.6218e-01,
           1.2839e+00, -1.2251e+00],
         [ 4.8338e-01,  1.5696e+00, -7.2131e-01,  ..., -6.4744e-01,
           8.2422e-03, -6.0463e-01],
         ...,
         [-1.6825e+00,  1

In [114]:
import numpy as np
import torch
import torch.nn as nn

eps = 10**-6
alpha = np.ones((1,)) 
bias = np.zeros((1,))
x = np.random.rand(2, 10, 512)
mean = x.mean(axis = -1, keepdims=True) # Computing the mean of the input data. Keeping the number of dimensions unchanged
std = x.std(axis = -1, keepdims=True) # Computing the standard deviation of the input data. Keeping the number of dimensions unchanged
        
alpha * (x-mean) / (std + eps) + bias

array([[[ 1.406948  ,  1.25346707, -0.42135117, ..., -0.97828444,
          1.6543173 , -0.46640261],
        [ 0.59150044,  0.99039293, -0.40004363, ...,  0.21679665,
         -0.37536094,  0.17018866],
        [-0.90687934,  0.31464981, -0.90301743, ...,  0.65993653,
         -1.31050138,  0.54569101],
        ...,
        [-1.21250908, -0.27937219, -0.00859462, ..., -0.19181777,
          1.17208064,  1.01407876],
        [-0.01594736, -0.2376258 ,  1.3790151 , ...,  1.01714823,
          0.70535331,  0.12603634],
        [-0.29881791, -1.56283988, -0.63784847, ...,  1.31632397,
         -1.31980812,  1.00559515]],

       [[-1.49989245,  1.02475926, -0.1921105 , ..., -0.04745001,
         -1.34603429, -0.78242785],
        [-0.70973579,  1.41222795, -0.24558219, ...,  0.42040351,
          0.5467505 , -0.28627766],
        [ 0.91151198, -0.03843883, -0.51292036, ..., -1.30789123,
         -0.96578559,  0.10643825],
        ...,
        [ 1.590901  , -0.60996341, -0.20250717, ...,  

## feed forward test

In [29]:
import numpy as np

class Dropout:
    def __init__(self, dropout_rate=0.5):
        self.dropout_rate = dropout_rate
        self.mask = None
    
    def forward(self, x, train_flag=True):
        # 학습 시
        if train_flag:
            self.mask = np.random.rand(*x.shape) > self.dropout_rate
            return x * self.mask
        else:
            return x * (1.0 - self.dropout_rate)
    
    def backward(self, dout):
        return dout * self.mask

class ReLU:
    
    def __init__(self):
        pass
    
    def forward(self, x):
        return np.maximum(0, x)
    
    def backward(self, x, grad_output):
        relu_grad = x > 0
        return grad_output * relu_grad

class FeedForwardBlock:
    
    def __init__(self, d_model: int, d_ff: int, dropout: float) -> None:
        # forward만 구현, random한 값으로 임의 init
        self.W1 = np.random.randn(d_model, d_ff) 
        self.b1 = np.random.randn(d_ff)
        self.W2 = np.random.randn(d_ff, d_model)
        self.b2 = np.random.randn(d_model)
        
        self.actiavation = ReLU()
        self.dropout = Dropout(dropout)
        
    def forward(self, x):
        # (Batch, seq_len, d_model) --> (batch, seq_len, d_ff)
        linear_1 = self.dropout.forward(self.actiavation.forward(np.dot(x, self.W1) + self.b1))
        
        # (batch, seq_len, d_ff) -->(batch, seq_len, d_model)
        linear_2 = np.dot(linear_1, self.W2) + self.b2
        return linear_2

FeedForwardBlock(512, 2048, 0.1).forward(np.random.rand(2, 10, 512)).shape

(2, 10, 512)