In [1]:
import torch
pe = torch.zeros(3, 4)
print(pe)
print(pe[:, 0::2])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [59]:
a = torch.rand(3,5)
a.shape[1]

5

In [12]:
torch.arange(0, 10, dtype = torch.float).unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [19]:
import math
-math.log(10000.0)

-9.210340371976184

In [60]:
seq_len, d_model = 5, 6
pe = torch.zeros(seq_len, d_model) 

# Creating a tensor representing positions (0 to seq_len - 1)
position = torch.arange(0, seq_len, dtype = torch.float).unsqueeze(1) # Transforming 'position' into a 2D tensor['seq_len, 1']

# Creating the division term for the positional encoding formula
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

# Apply sine to even indices in pe
pe[:, 0::2] = torch.sin(position * div_term)
# Apply cosine to odd indices in pe
pe[:, 1::2] = torch.cos(position * div_term)
pe = pe.unsqueeze(0)


In [63]:
batch_size, seq_len, d_model =2, 5, 6
pe = torch.zeros(batch_size, seq_len, d_model) 
pe.shape[2]

6

In [80]:
from embedding.pt_position import PositionalEncoding

pos_encoding = PositionalEncoding(d_model=512, seq_len=10, dropout=0.1)
print(pos_encoding.pe.shape)
x = torch.rand(5, 10, 512)
output = pos_encoding(x)
output.shape

torch.Size([1, 10, 512])


torch.Size([5, 10, 512])

In [95]:

import numpy as np
import math

d_model = 512
seq_len = 10

position = np.arange(seq_len, dtype=float)[:, np.newaxis] 
div_term = np.exp(np.arange(0, d_model, 2, dtype=float)) #* -(np.log(10000.0) / d_model))
pe = np.zeros((seq_len, d_model))
pe[:, 0::2] = np.sin(position * div_term)
# Apply cosine to odd indices in pe
pe[:, 1::2] = np.cos(position * div_term)
pe = np.expand_dims(pe, axis=0)
pe.shape
# x = np.random.rand(5, 10, 512)

pe[:, :x.shape[1]].shape

(1, 10, 512)

In [96]:
import numpy as np

# pe 배열: (1, 4, 3) 형태의 3차원 배열
pe = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

# x 배열: (2, 2, 3) 형태의 3차원 배열
x = np.random.rand(2, 2, 3)

# pe[:, :x.shape[1]] 사용
result1 = pe[:, :x.shape[1]]
print(result1)
print("Shape of result1:", result1.shape)

# pe[:, :x.shape[1], :] 사용
result2 = pe[:, :x.shape[1], :]
print(result2)
print("Shape of result2:", result2.shape)

[[[1 2 3]
  [4 5 6]]]
Shape of result1: (1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
Shape of result2: (1, 2, 3)
